// <auto-generated />
using System;
using CF9Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CF9Project.Migrations
{
    [DbContext(typeof(ProjectMvc9Context))]
    [Migration("20260717075905_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CF9Project.Models.Capability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_Capabilities_Name");

                    b.HasIndex(new[] { "Name" }, "UQ_Capabilities_Name")
                        .IsUnique();

                    b.ToTable("Capabilities");
                });

            modelBuilder.Entity("CF9Project.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GameCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Description" }, "IX_Games_Description");

                    b.HasIndex(new[] { "GameCompanyId" }, "IX_Games_GameCompanyId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("CF9Project.Models.GameCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_GameCompanys_UserId")
                        .IsUnique();

                    b.ToTable("GameCompanies");
                });

            modelBuilder.Entity("CF9Project.Models.Gamer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_Students_UserId")
                        .IsUnique();

                    b.ToTable("Gamers");
                });

            modelBuilder.Entity("CF9Project.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_Roles_Name");

                    b.HasIndex(new[] { "Name" }, "UQ_Roles_Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CF9Project.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "RoleId" }, "IX_Users_RoleId");

                    b.HasIndex(new[] { "Username" }, "IX_Users_Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GamesGamers", b =>
                {
                    b.Property<int>("GamersId")
                        .HasColumnType("int");

                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.HasKey("GamersId", "GamesId");

                    b.HasIndex("GamesId");

                    b.ToTable("GamesGamers");
                });

            modelBuilder.Entity("RolesCapabilities", b =>
                {
                    b.Property<int>("CapabilitiesId")
                        .HasColumnType("int");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.HasKey("CapabilitiesId", "RolesId");

                    b.HasIndex("CapabilitiesId")
                        .HasDatabaseName("IX_RolesCapabilities_CapabilityId");

                    b.HasIndex("RolesId");

                    b.ToTable("RolesCapabilities");
                });

            modelBuilder.Entity("CF9Project.Models.Game", b =>
                {
                    b.HasOne("CF9Project.Models.GameCompany", "GameCompany")
                        .WithMany("Games")
                        .HasForeignKey("GameCompanyId")
                        .HasConstraintName("FK_Games_GameCompanyId");

                    b.Navigation("GameCompany");
                });

            modelBuilder.Entity("CF9Project.Models.GameCompany", b =>
                {
                    b.HasOne("CF9Project.Models.User", "User")
                        .WithOne("GameCompany")
                        .HasForeignKey("CF9Project.Models.GameCompany", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GameCompanys_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CF9Project.Models.Gamer", b =>
                {
                    b.HasOne("CF9Project.Models.User", "User")
                        .WithOne("Gamer")
                        .HasForeignKey("CF9Project.Models.Gamer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Gamer_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CF9Project.Models.User", b =>
                {
                    b.HasOne("CF9Project.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Users_RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GamesGamers", b =>
                {
                    b.HasOne("CF9Project.Models.Gamer", null)
                        .WithMany()
                        .HasForeignKey("GamersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CF9Project.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RolesCapabilities", b =>
                {
                    b.HasOne("CF9Project.Models.Capability", null)
                        .WithMany()
                        .HasForeignKey("CapabilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CF9Project.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CF9Project.Models.GameCompany", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("CF9Project.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CF9Project.Models.User", b =>
                {
                    b.Navigation("GameCompany");

                    b.Navigation("Gamer");
                });
#pragma warning restore 612, 618
        }
    }
}
